### ISSUE TITLE
the requirement of file

### ISSUE THREAD

**Issue by tongyt1225** [LouisFaure/sensoryfates_paper#1]
the file p2w_sensory.rds do not exist Pseudotime_analysis.Rmd, could you offer it?

**Comment by LouisFaure** [comment]
Thank you for your interest in our study! The pagoda2 web object is available on GEO Database via the following [link](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE150150&format=file&file=GSE150150%5Fp2w%5Fsensory%2Erds%2Egz)
